FROM metabase/metabase:latest

# Можно добавить дополнительные настройки если нужно
# ENV MB_DB_TYPE=postgres
# ENV MB_DB_DBNAME=metabase
# ENV MB_DB_HOST=postgres_dwh
# ENV MB_DB_PORT=5432
# ENV MB_DB_USER=postgres
# ENV MB_DB_PASS=postgres

EXPOSE 3000
